var mongoose = require('mongoose'); 
var Schema = mongoose.Schema;

var contractSchema = mongoose.Schema({
  	isSigned              : {type : Boolean, default : false},
    isSent                : {type : Boolean, default : false},
    isAccepted            : {type: Boolean, default : false},
    isViewed              : {type: Boolean, default : false},
    place                 : String,
    contractDate          : Date,
    startDate             : Date,
    endDate               : Date,
    client                : String,
    clientOwnership       : String,
    clientCompany         : String,                    // useless, remove later  //offererCompany
    freelancer            : String,
    freelanceCompany      : String,                    // useless, remove later  // AcceptorCompany
    freelanceTitle        : String,
    freelanceOwnership    : String,
    workSubject           : String,
    description           : String,
    iterations            : Number,
    iterationFee          : Number,
    fee                   : Number,
    feeType               : String,
    proratedType          : String,
    advancePayment        : Number,
    milestone             : Object,
    latePayment           : Number,
    expenses              : String,
    currency              : String,
  //username              : String,
    email                 : String,
    owernship             : String,
    termination           : String,
    agreement             : String,
    agreement2            : String,
    terminationDays       : Number,
    paymentDays           : Number,
    invoiceDays           : Number,
    terminationFee        : String,
    ipMade                : String,
    acceptor              : String,
    acceptorIP            : String,
    acceptorSignature     : String,
    acceptorSignatureDate : Date,
    acceptorViewDate      : Date,
    acceptorEmail         : String,
    acceptorCompany       : String,
    offerer               : String,
    offererIP             : String,
    offererSignature      : String,
    offererSignatureDate  : Date,
    offererEmail          : String,
    offererCompany        : String,
    addendum              : String,
    viewDate              : Date,  // date when acceptor views the contract for the first time
    viewIP                : String //ip when first viewed by the acceptor
})

module.exports = mongoose.model('contracts', contractSchema);